# fly.toml app configuration file generated for bunnypresso on 2023-06-14T22:16:08+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bunnypresso"
primary_region = "nrt"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
